---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - neon.tech
  resources:
  - branches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - neon.tech
  resources:
  - branches/finalizers
  verbs:
  - update
- apiGroups:
  - neon.tech
  resources:
  - branches/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - neon.tech
  resources:
  - endpoints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - neon.tech
  resources:
  - endpoints/finalizers
  verbs:
  - update
- apiGroups:
  - neon.tech
  resources:
  - endpoints/status
  verbs:
  - get
  - patch
  - update
