apiVersion: neon.tech/v1alpha1
kind: Branch
metadata:
  labels:
    app.kubernetes.io/name: branch
    app.kubernetes.io/instance: branch-sample
    app.kubernetes.io/part-of: hackneon-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: hackneon-operator
  name: branch-sample
spec:
  # TODO(user): Add fields here
